### ISSUE TITLE
Two-way SSL broken with API 21

### ISSUE THREAD

**Issue by jason-callaway** [otohdotio/otoh.io-android-client#5]
postWithJSONCert in otoh.java seems to be broken with API 21 whereas it worked with API 19.

I'm also using a Nexus 6 now as my test device as opposed to my old Galaxy S5, but I doubt that's the root cause.

```
-----END CERTIFICATE-----
02-07 19:00:22.183    7867-7887/io.otoh.otohio I/System.out﹕ PUT https://api.otoh.io/0.1/certificates/test201502073 - {"csr":"-----BEGIN CERTIFICATE REQUEST-----\nMIIBojCCAUwCAQAwfTEZMBcGA1UEAxMQdGVzdDIwMTUwMjA3My1rZTENMAsGA1UEC\nxMEb3RvaDEdMBsGA1UEChMUQ2F0b2N0aW4gU3lzdGVtcyBMTEMxEjAQBgNVBAcTCU\nZyZWRlcmljazERMA8GA1UECBMITWFyeWxhbmQxCzAJBgNVBAYTAlVTMFwwDQYJKoZ\nIhvcNAQEBBQADSwAwSAJBAPilwG6erOfQdN\/QmfrtiKK5s\/D7yFZdwchtJ9xHYju4\n4KMCzZMk5GbqnubIRU8NV0M9VQ4V4nHxdjO0zuKtKgUCAwEAAaBqMGgGCSqGSIb3D\nQEJDjFbMFkwVwYDVR0RBFAwToEZdGVzdDIwMTUwMjA3M0BleGFtcGxlLmNvbaAxBg\nMqAwSgKgwoMmU0Mzc3YTUwZDdmOTRkNGIxZDdhYmZiMDA4Yzc1ZjY2ODk1MzA2ZDA\nNBgkqhkiG9w0BAQsFAANBAHBd2jwRg1Oj24R5wvcoAWajAMEwoJhQs+tgJn9XvlvR\n6i8KpEnchJPRXhvWH6B0sUmr+hE6T02b2RBkafNHF8Q=\n-----END CERTIFICATE REQUEST-----","key_use":"ke","username":"test201502073","identity_name":"test201502073@work"}
02-07 19:00:22.670    7867-7887/io.otoh.otohio E/+++++debug﹕ exception caught
02-07 19:00:22.670    7867-7887/io.otoh.otohio W/System.err﹕ javax.net.ssl.SSLHandshakeException: Handshake failed
02-07 19:00:22.670    7867-7887/io.otoh.otohio W/System.err﹕ at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:374)
02-07 19:00:22.670    7867-7887/io.otoh.otohio W/System.err﹕ at com.android.okhttp.Connection.upgradeToTls(Connection.java:197)
02-07 19:00:22.671    7867-7887/io.otoh.otohio W/System.err﹕ at com.android.okhttp.Connection.connect(Connection.java:151)
02-07 19:00:22.671    7867-7887/io.otoh.otohio W/System.err﹕ at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
02-07 19:00:22.671    7867-7887/io.otoh.otohio W/System.err﹕ at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
02-07 19:00:22.671    7867-7887/io.otoh.otohio W/System.err﹕ at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:373)
02-07 19:00:22.671    7867-7887/io.otoh.otohio W/System.err﹕ at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:323)
02-07 19:00:22.671    7867-7887/io.otoh.otohio W/System.err﹕ at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:491)
02-07 19:00:22.671    7867-7887/io.otoh.otohio W/System.err﹕ at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
02-07 19:00:22.671    7867-7887/io.otoh.otohio W/System.err﹕ at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
02-07 19:00:22.671    7867-7887/io.otoh.otohio W/System.err﹕ at io.otoh.otohio.otoh.postWithJSONCert(otoh.java:207)
02-07 19:00:22.671    7867-7887/io.otoh.otohio W/System.err﹕ at io.otoh.otohio.otoh.createCertificate(otoh.java:372)
02-07 19:00:22.671    7867-7887/io.otoh.otohio W/System.err﹕ at io.otoh.otohio.GenIdentityActivity$1.doInBackground(GenIdentityActivity.java:202)
02-07 19:00:22.671    7867-7887/io.otoh.otohio W/System.err﹕ at io.otoh.otohio.GenIdentityActivity$1.doInBackground(GenIdentityActivity.java:91)
02-07 19:00:22.671    7867-7887/io.otoh.otohio W/System.err﹕ at android.os.AsyncTask$2.call(AsyncTask.java:288)
02-07 19:00:22.671    7867-7887/io.otoh.otohio W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-07 19:00:22.671    7867-7887/io.otoh.otohio W/System.err﹕ at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
02-07 19:00:22.671    7867-7887/io.otoh.otohio W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
02-07 19:00:22.671    7867-7887/io.otoh.otohio W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
02-07 19:00:22.671    7867-7887/io.otoh.otohio W/System.err﹕ at java.lang.Thread.run(Thread.java:818)
02-07 19:00:22.671    7867-7887/io.otoh.otohio W/System.err﹕ Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xa11b9800: Failure in SSL library, usually a protocol error
02-07 19:00:22.671    7867-7887/io.otoh.otohio W/System.err﹕ error:1407743E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert inappropriate fallback (external/openssl/ssl/s23_clnt.c:765 0xac4d0e61:0x00000000)
02-07 19:00:22.671    7867-7887/io.otoh.otohio W/System.err﹕ at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
02-07 19:00:22.671    7867-7887/io.otoh.otohio W/System.err﹕ at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:302)
02-07 19:00:22.671    7867-7887/io.otoh.otohio W/System.err﹕ ... 19 more
```

**Comment by jason-callaway** [comment]
Seems to be related to this: http://developer.android.com/about/versions/android-5.0-changes.html#ssl

> These changes may lead to breakages in HTTPS or TLS/SSL connectivity in a small number of cases listed below.
